*AIRBAG_HYBRID_ID
$#    abid heading

$#     sid    sidtyp      rbid      vsca      psca      vini       mwd      spsf

$#  atmost    atmosp    atmosd        gc        cc     hconv

$#     c23     lcc23       a23     lca23      cp23     lcp23      ap23    lcap23

$#     opt     pvent      ngas     lcefr    lcidmo    vntopt

$#   lcidm     lcidt                  mw     initm         a         b         c

$#   fmass

$
