*SET_NODE_GENERAL_TITLE
$# title
?title?
$#     sid       da1       da2       da3       da4    solver
         ?
$#  option        e1        e2        e3        e4        e5        e6        e7
ALL
NODE               ?
DNODE              ?
PART               ?
DPART              ?
BOX                ?
DBOX               ?
VOL                ?
DVOL               ?
SET_SHELL          ?
SET_SOLID          ?
SET_BEAM           ?
SET_TSHELL         ?
SET_SPRING         ?
$
