*CONTACT_TIED_SHELL_EDGE_TO_SURFACE_BEAM_OFFSET_ID
$#     cid title
         ? ?title?
$#    ssid      msid     sstyp     mstyp    sboxid    mboxid       spr       mpr
         ?         ?         ?         ?
$#      fs        fd        dc        vc       vdc    penchk        bt        dt

$#     sfs       sfm       sst       mst      sfst      sfmt       fsf       vsf
                                      -?
$
