*PART_INERTIA
$# title
?title?
$#     pid     secid       mid     eosid      hgid      grav    adpopt      tmid
         ?         ?         ?
$#      xc        yc        zc        tm      ircs    nodeid
         ?         ?         ?         ?
$#     ixx       ixy       ixz       iyy       iyz       izz
         ?         ?         ?         ?         ?         ?
$#     vtx       vty       vtz       vrx       vry       vrz

$
