*CONTROL_CONTACT
$#  slsfac    rwpnal    islchk    shlthk    penopt    thkchg     orien    enmass

$#  usrstr    usrfrc     nsbcs    interm     xpene     ssthk      ecdt   tiedprj

$#   sfric     drfic       edc       vfc        th     th_sf    pen_sf

$#  ignore    frceng   skiprwg    outseg   spotstp   spotdel   spothin

$#    isym    nserod    rwgaps    rwgdth     rwksf      icov    swradf    ithoff

$#  shledg    pstiff    ithcnt    tdcnof     ftall              shltrw

$
