*MAT_NONLINEAR_PLASTIC_DISCRETE_BEAM_TITLE
$# title
?title?
$#     mid        ro       tkr       tks       tkt       rkr       rks       rkt
         ?         ?
$#     rdr       rds       rdt       rdr       rds       rdt

$#   lcpdr     lcpds     lcpdt     lcpmr     lcpms     lcpmt

$#  ffailr    ffails    ffailt    mfailr    mfails    mfailt

$#  ufailr    ufails    ufailt    tfailr    tfails    tfailt

$#     for       fos       fot       mor       mos       mot

$
