*LOAD_BODY_Z
$#    lcid        sf    lciddr        xc        yc        zc       cid
         2       1.0
*DEFINE_CURVE_TITLE
$# title
Gravity_mmkgms
$#    lcid      sidr       sfa       sfo      offa      offo    dattyp
         2         0       1.0       1.0       0.0       0.0
$#         time [ms]       acc [mm/ms^2]
                 0.0            9.81e-03
             1.0e+06            9.81e-03
$
