*MAT_NONLINEAR_ELASTIC_DISCRETE_BEAM_TITLE
$# title
?title?
$#     mid        ro    lcidtr    lcidts    lcidtt    lcidrr    lcidrs    lcidrt
         ?         ?
$# lcidtdr   lcidtds   lcidtdt   lcidrdr   lcidrds   lcidrdt

$#     for       fos       fot       mor       mos       mot

$#  ffailr    ffails    ffailt    mfailr    mfails    mfailt

$#  ufailr    ufails    ufailt    tfailr    tfails    tfailt

$
